/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as TransportadorasRouteImport } from './routes/transportadoras'
import { Route as RastreamentoRouteImport } from './routes/rastreamento'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContratacoesRouteImport } from './routes/contratacoes'
import { Route as AuditoriaRouteImport } from './routes/auditoria'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CotacoesIndexRouteImport } from './routes/cotacoes.index'
import { Route as CotacoesResultadoRouteImport } from './routes/cotacoes.resultado'
import { Route as CotacoesNovaRouteImport } from './routes/cotacoes.nova'

const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const TransportadorasRoute = TransportadorasRouteImport.update({
  id: '/transportadoras',
  path: '/transportadoras',
  getParentRoute: () => rootRouteImport,
} as any)
const RastreamentoRoute = RastreamentoRouteImport.update({
  id: '/rastreamento',
  path: '/rastreamento',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContratacoesRoute = ContratacoesRouteImport.update({
  id: '/contratacoes',
  path: '/contratacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditoriaRoute = AuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CotacoesIndexRoute = CotacoesIndexRouteImport.update({
  id: '/cotacoes/',
  path: '/cotacoes/',
  getParentRoute: () => rootRouteImport,
} as any)
const CotacoesResultadoRoute = CotacoesResultadoRouteImport.update({
  id: '/cotacoes/resultado',
  path: '/cotacoes/resultado',
  getParentRoute: () => rootRouteImport,
} as any)
const CotacoesNovaRoute = CotacoesNovaRouteImport.update({
  id: '/cotacoes/nova',
  path: '/cotacoes/nova',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auditoria': typeof AuditoriaRoute
  '/contratacoes': typeof ContratacoesRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/rastreamento': typeof RastreamentoRoute
  '/transportadoras': typeof TransportadorasRoute
  '/usuarios': typeof UsuariosRoute
  '/cotacoes/nova': typeof CotacoesNovaRoute
  '/cotacoes/resultado': typeof CotacoesResultadoRoute
  '/cotacoes/': typeof CotacoesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auditoria': typeof AuditoriaRoute
  '/contratacoes': typeof ContratacoesRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/rastreamento': typeof RastreamentoRoute
  '/transportadoras': typeof TransportadorasRoute
  '/usuarios': typeof UsuariosRoute
  '/cotacoes/nova': typeof CotacoesNovaRoute
  '/cotacoes/resultado': typeof CotacoesResultadoRoute
  '/cotacoes': typeof CotacoesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auditoria': typeof AuditoriaRoute
  '/contratacoes': typeof ContratacoesRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/rastreamento': typeof RastreamentoRoute
  '/transportadoras': typeof TransportadorasRoute
  '/usuarios': typeof UsuariosRoute
  '/cotacoes/nova': typeof CotacoesNovaRoute
  '/cotacoes/resultado': typeof CotacoesResultadoRoute
  '/cotacoes/': typeof CotacoesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auditoria'
    | '/contratacoes'
    | '/login'
    | '/logs'
    | '/rastreamento'
    | '/transportadoras'
    | '/usuarios'
    | '/cotacoes/nova'
    | '/cotacoes/resultado'
    | '/cotacoes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auditoria'
    | '/contratacoes'
    | '/login'
    | '/logs'
    | '/rastreamento'
    | '/transportadoras'
    | '/usuarios'
    | '/cotacoes/nova'
    | '/cotacoes/resultado'
    | '/cotacoes'
  id:
    | '__root__'
    | '/'
    | '/auditoria'
    | '/contratacoes'
    | '/login'
    | '/logs'
    | '/rastreamento'
    | '/transportadoras'
    | '/usuarios'
    | '/cotacoes/nova'
    | '/cotacoes/resultado'
    | '/cotacoes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditoriaRoute: typeof AuditoriaRoute
  ContratacoesRoute: typeof ContratacoesRoute
  LoginRoute: typeof LoginRoute
  LogsRoute: typeof LogsRoute
  RastreamentoRoute: typeof RastreamentoRoute
  TransportadorasRoute: typeof TransportadorasRoute
  UsuariosRoute: typeof UsuariosRoute
  CotacoesNovaRoute: typeof CotacoesNovaRoute
  CotacoesResultadoRoute: typeof CotacoesResultadoRoute
  CotacoesIndexRoute: typeof CotacoesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transportadoras': {
      id: '/transportadoras'
      path: '/transportadoras'
      fullPath: '/transportadoras'
      preLoaderRoute: typeof TransportadorasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rastreamento': {
      id: '/rastreamento'
      path: '/rastreamento'
      fullPath: '/rastreamento'
      preLoaderRoute: typeof RastreamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contratacoes': {
      id: '/contratacoes'
      path: '/contratacoes'
      fullPath: '/contratacoes'
      preLoaderRoute: typeof ContratacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auditoria': {
      id: '/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuditoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cotacoes/': {
      id: '/cotacoes/'
      path: '/cotacoes'
      fullPath: '/cotacoes/'
      preLoaderRoute: typeof CotacoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cotacoes/resultado': {
      id: '/cotacoes/resultado'
      path: '/cotacoes/resultado'
      fullPath: '/cotacoes/resultado'
      preLoaderRoute: typeof CotacoesResultadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cotacoes/nova': {
      id: '/cotacoes/nova'
      path: '/cotacoes/nova'
      fullPath: '/cotacoes/nova'
      preLoaderRoute: typeof CotacoesNovaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditoriaRoute: AuditoriaRoute,
  ContratacoesRoute: ContratacoesRoute,
  LoginRoute: LoginRoute,
  LogsRoute: LogsRoute,
  RastreamentoRoute: RastreamentoRoute,
  TransportadorasRoute: TransportadorasRoute,
  UsuariosRoute: UsuariosRoute,
  CotacoesNovaRoute: CotacoesNovaRoute,
  CotacoesResultadoRoute: CotacoesResultadoRoute,
  CotacoesIndexRoute: CotacoesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
